# Generated by Django 5.0 on 2025-11-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_major_alter_studentprofile_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
