# Generated by Django 5.0 on 2025-11-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tutorprofile_subjects'),
        ('accounts', '0004_friendship_friendship_unique_friend_pair'),
    ]

    operations = [
    ]
