# Generated by Django 5.0 on 2025-11-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_tutorprofile_location_studentprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='study_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='study_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='study_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='study_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='study_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='study_longitude',
            new_name='longitude',
        ),
    ]
