# Generated by Django 5.0 on 2025-12-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_friendrequest_friendrequest_unique_friend_request'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='classes.class'),
        ),
    ]
