# Generated by Django 5.0 on 2025-12-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentprofile_classes'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='classes.class'),
        ),
    ]
