# Generated by Django 5.0 on 2025-12-08 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tutorprofile_classes'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(choices=[(1, 'Need Help'), (2, 'Beginner'), (3, 'Comfortable'), (4, 'Intermediate'), (5, 'Strong/Advanced')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_skills', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['class_taken__name'],
                'unique_together': {('student', 'class_taken')},
            },
        ),
    ]
