# Generated by Django 5.0 on 2025-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_studentclassskill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="classes",
        ),
        migrations.AlterField(
            model_name="studentclassskill",
            name="skill_level",
            field=models.IntegerField(
                choices=[
                    (1, "Need Help"),
                    (2, "Learning"),
                    (3, "Comfortable"),
                    (4, "Confident"),
                    (5, "Expert"),
                ],
                default=3,
            ),
        ),
    ]
