# Generated by Django 5.0 on 2025-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_studentprofile_classes_and_more'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='classes.class'),
        ),
    ]
