# Generated by Django 5.0 on 2025-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoringsession', '0002_alter_tutoringsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutoringsession',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
