# Generated by Django 5.0 on 2025-12-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('tutoringsession', '0003_alter_tutoringsession_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classes.class'),
        ),
    ]
